### ISSUE TITLE
Question about euvoc

### ISSUE THREAD

**Issue by jimjyang** [eu-vocabularies/SKOS-AP-EU#3]
Where can I find more documentation of the whole euvoc (Publications Office Extensions Ontology)? The URI, http://publications.europa.eu/ontology/euvoc what is in the PDF-documentation of SKOS-AP-EU doesn't work. 

[Background for my question: We have also established a national application profile of SKOS, as our national standard for publishing concept descriptions / controlled vocabularies for the public sector in Norway. I am therefore very interested in learning more about the ontology euvoc.]

**Comment by costezki** [comment]
Dear Jim, 
 the EuVoc Ontology is part of CDM (Common Data Model) governing the Cellar, the triple store where official journal and many other documents are stored (including the document metadata). 

CDM is published on the EU Vocabularies website on [this page](https://op.europa.eu/en/web/eu-vocabularies/model/-/resource/dataset/cdm). If you download the Zip archive, you will find inside the `euvoc.rdf` module. 
Generally, the EuVoc ontology serves only one purpose, to define specific properties and classes that are used in the application profiles: SKOS-AP-EU, ORG-AP-EU and DCAT-AP-EU (no longer sure if DCAT-AP is covered).

I hope this helps

**Comment by jimjyang** [comment]
Thanks, @costezki! Yes, that helps!
