### ISSUE TITLE
Question: What is the URI for SKOS-AP-EU?

### ISSUE THREAD

**Issue by jimjyang** [eu-vocabularies/SKOS-AP-EU#4]
We are reusing parts of SKOS-AP-EU in our Norwegian application profile of SKOS. 

I don't remember where I got the URI `http://publications.europa.eu/ontology/euvoc`, but I get now `301 Moved Permanently` when I curl on that URI. 

Where is the ontology for SKOS-AP-EU moved to now,. or, what is the official URI for this ontology? 

I hope that the ontology for SKOS-AP-EU is available as a machine-accessible and machine-readable RDF resource.

**Comment by costezki** [comment]
@jimjyang the EuVoc ontology is part of CDM (Cellar Common Data Model) available here

https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/cdm

The SKOS-AP-EU has not been established in SHACL format. Its components were developed ~4-5 years ago and can be accessed here:
https://op.europa.eu/en/web/eu-vocabularies/application-profiles

![image](https://github.com/meaningfy-ws/SKOS-AP-EU/assets/13567133/a9700426-f3b6-4518-af92-89412ec60aca)

To my knowledge, there is some work ongoing to revise the SKOS-AP-EU, but I cannot tell when will that be released. 
It is best to get in touch with the OP on this topic.
